### PR TITLE
Cart model, View and Remove functionality, closes #5

### LINKED ISSUE #5: Adding Items to the Cart
Background: Items, and a user that is not logged in
  As a visitor
  When I visit any page with an item on it
  I should see a link or button for "Add to Cart"
  When I click "Add to cart" for that item
  And I click a link or button to view cart
  And my current path should be "/cart"
  And I should see a small image, title, description and price for the item I just added
  And there should be a "total" price for the cart that should be the sum of all items in the cart

### PR DESCRIPTION
**Pull request by Laszlo-JFLMTCO**
@drod1000 @njgheorghita @Dpalazzari 

All tests passed after local merge with latest Master.

### CODE REVIEW

**Comment by drod1000** [comment]
Looks good!

**Comment by njgheorghita** [comment]
looks ready to commit to master!

**Comment by njgheorghita** [comment]
@Dpalazzari if it's looking good to you go ahead and merge that pull request

**Comment by Dpalazzari** [comment]
Looking real good fellas. Mergin'.

**Pull request merged**
