### PR TITLE
closes #4

### LINKED ISSUE #4: Browsing Items by category
Background: I have two categories with titles and each has two different items assigned
  As a visitor
  When I visit "/:CATEGORY_NAME"
  I see all items assigned to that category

### PR DESCRIPTION
**Pull request by drod1000**

### CODE REVIEW

**Comment by drod1000** [comment]
@Dpalazzari @njgheorghita @Laszlo-JFLMTCO 
View Outing by Politician completed

I reused part of the view from outings index and extracted it into shared partial

I also noticed that our routes had both of these which do the same thing so I just used the top one
resources :outings, only: [:index]
get 'outings' => 'outings#index'

Please let me know what you guys think

**Comment by Dpalazzari** [comment]
👍 looks good to me.

**Comment by njgheorghita** [comment]
yeah, i like it too @Laszlo-JFLMTCO go ahead with the merge if its good with you

**Comment by Laszlo-JFLMTCO** [comment]
Looks good to me, too! @drod1000  good find with the redundant routes! I will merge it into Master and use it as a baseline to apply formatting to #5 and #6.

**Pull request merged**
